ePayRoll/Controllers/PayslipController.cs
using ePayRoll.Models;
using Microsoft.Reporting.WebForms;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ePayRoll.Controllers
{
    public class PayslipController : Controller
    {
		private readonly string apiUrl;

		public PayslipController()
		{
			apiUrl = ConfigurationManager.AppSettings["ApiBaseUrl"] + "payroll/";
		}

		// GET: PaySlip List by MonthYear
		public async Task<ActionResult> Index(string selectedMonthYear)
        {
			if (string.IsNullOrEmpty(selectedMonthYear))
				selectedMonthYear = DateTime.Now.ToString("yyyy-MM");

			DateTime selectedDate = DateTime.ParseExact(selectedMonthYear, "yyyy-MM", null);
			int selectedYear = selectedDate.Year;
			int selectedMonth = selectedDate.Month;

			HttpClient client = new HttpClient();
			HttpResponseMessage response = await client.GetAsync(apiUrl + $"processed/{selectedYear}/{selectedMonth}");

			List<ProcessedSalary> salaries = new List<ProcessedSalary>();
			if (response.IsSuccessStatusCode)
			{
				string jsonData = await response.Content.ReadAsStringAsync();
				salaries = JsonConvert.DeserializeObject<List<ProcessedSalary>>(jsonData);
			}

			return View(salaries);
		}

		// GET: Download PaySlip
		[HttpGet]
		public async Task<ActionResult> GeneratePaySlip(int payrollId)
		{
			HttpClient client = new HttpClient();
			HttpResponseMessage response = await client.GetAsync(apiUrl + "get-payroll/" + payrollId);

			if (!response.IsSuccessStatusCode)
				return HttpNotFound();

			string jsonData = await response.Content.ReadAsStringAsync();
			ProcessedSalary salary = JsonConvert.DeserializeObject<ProcessedSalary>(jsonData);

			LocalReport lr = new LocalReport();
			string path = Path.Combine(Server.MapPath("~/Reports"), "PaySlipReport.rdlc");
			lr.ReportPath = path;

			ReportDataSource rd = new ReportDataSource("PaySlipDataset", new List<ProcessedSalary> { salary });
			lr.DataSources.Add(rd);

			string mimeType, encoding, fileNameExtension;
			Warning[] warnings;
			string[] streams;
			byte[] renderedBytes = lr.Render("PDF", null, out mimeType, out encoding, out fileNameExtension, out streams, out warnings);

			return File(renderedBytes, "application/pdf", $"PaySlip_{salary.EmployeeName}_{salary.MonthYear:yyyyMM}.pdf");
		}

		// GET: View PaySlip
		[HttpGet]
		public async Task<ActionResult> ViewPaySlip(int payrollId)
		{
			HttpClient client = new HttpClient();
			HttpResponseMessage response = await client.GetAsync(apiUrl + "get-payroll/" + payrollId);

			if (!response.IsSuccessStatusCode)
				return HttpNotFound("Pay slip data not found!");

			string jsonData = await response.Content.ReadAsStringAsync();
			ProcessedSalary salary = JsonConvert.DeserializeObject<ProcessedSalary>(jsonData);

			LocalReport lr = new LocalReport();
			string reportPath = Path.Combine(Server.MapPath("~/Reports"), "PaySlipReport.rdlc");

			if (!System.IO.File.Exists(reportPath))
				throw new FileNotFoundException("PaySlipReport.rdlc not found!");

			lr.ReportPath = reportPath;

			string reportDataSetName = "PaySlipDataset";

			List<ProcessedSalary> paySlipData = new List<ProcessedSalary> { salary };

			ReportDataSource rd = new ReportDataSource(reportDataSetName, paySlipData);
			lr.DataSources.Clear();
			lr.DataSources.Add(rd);

			string mimeType, encoding, fileNameExtension;
			Warning[] warnings;
			string[] streams;

			byte[] renderedBytes = lr.Render("PDF", null, out mimeType, out encoding, out fileNameExtension, out streams, out warnings);

			return File(renderedBytes, "application/pdf");
		}


	}
}

ePayRoll/Views/Payslip/Index.cshtml
@model IEnumerable<ePayRoll.Models.ProcessedSalary>

<h2>Pay Slip List</h2>

<div class="row">
    <div class="col-auto">
        <label>Select Month:</label>
    </div>
    <div class="col-auto">
        <input type="month" id="salaryMonth" class="form-control" value="@DateTime.Now.ToString("yyyy-MM")" />
    </div>
    <div class="col-auto">
        <button id="loadSalariesBtn" class="btn btn-info">Search</button>
    </div>
</div>

<table class="table table-bordered mt-3">
    <thead>
        <tr>
            <th>Employee Name</th>
            <th>Month</th>
            <th>Basic Salary</th>
            <th>Allowances</th>
            <th>Deductions</th>
            <th>Net Salary</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var salary in Model)
        {
            <tr>
                <td>@salary.EmployeeName</td>
                <td>@salary.MonthYear.ToString("yyyy-MM")</td>
                <td>@salary.BasicSalary</td>
                <td>@salary.TotalAllowances</td>
                <td>@salary.TotalDeductions</td>
                <td>@salary.TotalSalary</td>
                <td>
                    <a href="@Url.Action("GeneratePaySlip", "Payslip", new { payrollId = salary.PayrollId })" class="btn btn-success">
                        Download PDF
                    </a>
                    <button class="btn btn-primary" onclick="viewPaySlip(@salary.PayrollId)">View</button>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <script>
    $(document).ready(function () {
        $("#loadSalariesBtn").click(function () {
            let selectedMonth = $("#salaryMonth").val();
            if (!selectedMonth) {
                alert("Please select a valid month.");
                return;
            }
            window.location.href = "@Url.Action("Index", "PaySlip")" + "?selectedMonthYear=" + selectedMonth;
        });
    });

    function viewPaySlip(payrollId) {
        let url = "@Url.Action("ViewPaySlip", "PaySlip")" + "?payrollId=" + payrollId;
        window.open(url, "_blank");
    }
    </script>
}

ePayRoll/Views/Payslip/ViewPaySlip.cshtml
@using Microsoft.Reporting.WebForms
@{
    ViewBag.Title = "Pay Slip Report";
}

<h2>Pay Slip Report</h2>


@if (ViewBag.ReportViewer != null)
{
    <form id="form1" runat="server">
        <rsweb:ReportViewer ID="ReportViewer1" runat="server" Width="100%" Height="600px"
                            ProcessingMode="Local" ShowPrintButton="True">
            <LocalReport ReportPath="~/Reports/PaySlipReport.rdlc">
            </LocalReport>
        </rsweb:ReportViewer>
    </form>
}
else
{
    <p>Error: Pay Slip data not found.</p>
}